# Generated by Django 4.2.4 on 2023-10-09 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_books_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='ISBN',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12), django.core.validators.RegexValidator('^[0-9]{12}$', 'Enter a 12-digit numeric value.')]),
        ),
    ]
