# Generated by Django 4.2.4 on 2023-10-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_books_borrowed_by_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
