# Generated by Django 4.2.4 on 2023-10-10 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_loan_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='returnbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('returned_date', models.DateTimeField(auto_now=True)),
                ('review', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.books')),
            ],
        ),
    ]
