# Generated by Django 4.2.4 on 2023-10-10 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=40)),
                ('book_req', models.CharField(max_length=20)),
                ('date_req', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=20)),
                ('publish', models.DateTimeField()),
                ('ISBN', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1200123)])),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/profile_pics'),
        ),
    ]
